{{- if eq .chezmoi.os "darwin" -}}
{{- $config_key := "personal" }}
{{- if .chezmoi.config.data.isWorkMachine }}
  {{- $config_key = "work" }}
{{- end -}}
{{- dig "external" $config_key (dict) . | toYaml }}
{{- end }}
